name: Build and Publish

on:
  push:
    branches:
      - main
permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: "temurin"
      - name: Inject Version File
        run: echo "${{ github.run_number }}" > src/main/resources/flint_version.txt
      - name: Build with Gradle
        run: ./gradlew build '-Pversion=${{ github.run_number }}'
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Flint
          path: ./build/libs/Flint*.jar
      - name: Publish Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ github.run_number }}"
          prerelease: false
          files: |
            ./build/libs/
      - name: Publish to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: dBv9so2c
          name: "Flint v${{ github.run_number }}"
          version: "v${{ github.run_number }}"
          changelog: "${{ github.event.head_commit.message }}"
          dependencies: |-
            [{
              "project_id": "P7dR8mSH",
              "dependency_type": "required"
            }]
          loaders: |-
            fabric
          game-versions: |-
            1.21.3
          files: '["./build/libs/Flint-1.0.0.jar", "./build/libs/Flint-1.0.0-sources.jar"]'
          primary-file: "Flint-1.0.0.jar"
